name: "Docker Release"

on:
  workflow_dispatch:
  push:
    branches: 
      - faucet-server-deployment

jobs:
  build-and-publish:
    runs-on: 
      - self-hosted
      - linux
      - x64
      - sre
    concurrency:
      group: docker-${{ github.ref }}
      cancel-in-progress: true
    strategy: 
      fail-fast: true
      
    steps:
    - name: Clean up
      continue-on-error: true
      run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE
        docker system prune --force --all --volumes

    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  

    - name: Build Faucet server
      run: |
        /home/runner/.cargo/bin/cargo build --release -p faucet-server
        gsutil cp target/release/faucet-server gs://composable-binaries/community-releases/utils/

    - name: Build Docker image
      run: RELEASE_VERSION=$(git tag --sort=committerdate | grep -E '^v[0-9]' | tail -1) make containerize-faucet-server 
    
    - name:  Docker push
      run: RELEASE_VERSION=$(git tag --sort=committerdate | grep -E '^v[0-9]' | tail -1) make push-faucet-server
